folio-org/ui-acquisition-units

.editorconfig
.eslintrc
.gitignore
CHANGELOG.md
CONTRIBUTING.md
LICENSE
PULL_REQUEST_TEMPLATE.md
README.md
package.json
src/index.js
src/settings/AcquisitionUnitsList.js
src/settings/index.js
test/bigtest/.eslintrc
test/bigtest/helpers/setup-application.js
test/bigtest/index.js
test/bigtest/interactors/Settings.js
test/bigtest/network/boot.js
test/bigtest/network/index.js
test/bigtest/tests/settings-test.js
translations/ui-acquisition-units/en.json

https://issues.folio.org/browse/UIAC-1

UIAC-1 Create 'Acquisition units' area in settings

---

translations/ui-acquisition-units/ar.json
translations/ui-acquisition-units/ca.json
translations/ui-acquisition-units/da.json
translations/ui-acquisition-units/de.json
translations/ui-acquisition-units/en_GB.json
translations/ui-acquisition-units/en_SE.json
translations/ui-acquisition-units/en_US.json
translations/ui-acquisition-units/es.json
translations/ui-acquisition-units/es_419.json
translations/ui-acquisition-units/es_ES.json
translations/ui-acquisition-units/fr.json
translations/ui-acquisition-units/fr_FR.json
translations/ui-acquisition-units/hu.json
translations/ui-acquisition-units/it_IT.json
translations/ui-acquisition-units/pt_BR.json
translations/ui-acquisition-units/pt_PT.json
translations/ui-acquisition-units/zh_CN.json

Update translation strings as of 20190703T132726

---

package.json
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetails.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsActions.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsContainer.js
src/settings/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEditor.js
src/settings/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEditorContainer.js
src/settings/AcquisitionUnits/AcquisitionUnitEditor/index.js
src/settings/AcquisitionUnits/AcquisitionUnits.js
src/settings/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsList.js
src/settings/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsListContainer.js
test/bigtest/interactors/AcquisitionUnitDetails.js
test/bigtest/interactors/AcquisitionUnitEditor.js
test/bigtest/interactors/AcquisitionUnitsList.js
test/bigtest/network/config.js
test/bigtest/network/configs/units.js
test/bigtest/network/configs/users.js
test/bigtest/network/factories/unit.js
test/bigtest/network/factories/user.js
test/bigtest/network/models/unit.js
test/bigtest/network/models/user.js
test/bigtest/network/serializers/application.js
test/bigtest/network/serializers/unit.js
test/bigtest/network/serializers/user.js
test/bigtest/tests/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetails-test.js
test/bigtest/tests/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitCreate-test.js
test/bigtest/tests/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEdit-test.js
test/bigtest/tests/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsList-test.js
translations/ui-acquisition-units/en.json

https://issues.folio.org/browse/UIAC-2
* use loading pane when it's in common components repo
* test for delete (common interactor)
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …

UIAC-2 create, edit, delete AC units

---

README.md

https://issues.folio.org/browse/UIAC-5 …

UIAC-5 Update README to describe the project

---

translations/ui-acquisition-units/ar.json
translations/ui-acquisition-units/ca.json
translations/ui-acquisition-units/da.json
translations/ui-acquisition-units/de.json
translations/ui-acquisition-units/en_GB.json
translations/ui-acquisition-units/en_SE.json
translations/ui-acquisition-units/en_US.json
translations/ui-acquisition-units/es.json
translations/ui-acquisition-units/es_419.json
translations/ui-acquisition-units/es_ES.json
translations/ui-acquisition-units/fr.json
translations/ui-acquisition-units/fr_FR.json
translations/ui-acquisition-units/hu.json
translations/ui-acquisition-units/it_IT.json
translations/ui-acquisition-units/pt_BR.json
translations/ui-acquisition-units/pt_PT.json
translations/ui-acquisition-units/zh_CN.json

Update translation strings as of 20190709T154346

---

translations/ui-acquisition-units/pt_BR.json

Update translation strings as of 20190711T172340

---

package.json
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetails.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsActions.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsContainer.js
src/settings/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEditor.js
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMemberships.js
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMembershipsContainer.js
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AssignAcquisitionUnitMemberships.css
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AssignAcquisitionUnitMemberships.js
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/index.js
src/settings/AcquisitionUnits/constants.js
src/settings/AcquisitionUnits/reducer.js
src/settings/AcquisitionUnits/resources.js
test/bigtest/interactors/AcquisitionUnitMemberships.js
test/bigtest/network/config.js
test/bigtest/network/configs/groups.js
test/bigtest/network/configs/memberships.js
test/bigtest/network/configs/units.js
test/bigtest/network/configs/users.js
test/bigtest/network/factories/group.js
test/bigtest/network/factories/membership.js
test/bigtest/network/models/group.js
test/bigtest/network/models/membership.js
test/bigtest/network/serializers/group.js
test/bigtest/network/serializers/membership.js
test/bigtest/tests/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsMembership-test.js
test/bigtest/tests/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitCreate-test.js
test/bigtest/tests/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEdit-test.js
translations/ui-acquisition-units/en.json

https://issues.folio.org/browse/UIAC-3
* Tests (avoid mirage errors)
* Multi select users …

UIAC-3 Assign and unassigned users to Acquisition units - single select

---

translations/ui-acquisition-units/ar.json
translations/ui-acquisition-units/ca.json
translations/ui-acquisition-units/da.json
translations/ui-acquisition-units/de.json
translations/ui-acquisition-units/en_GB.json
translations/ui-acquisition-units/en_SE.json
translations/ui-acquisition-units/en_US.json
translations/ui-acquisition-units/es.json
translations/ui-acquisition-units/es_419.json
translations/ui-acquisition-units/es_ES.json
translations/ui-acquisition-units/fr.json
translations/ui-acquisition-units/fr_FR.json
translations/ui-acquisition-units/hu.json
translations/ui-acquisition-units/it_IT.json
translations/ui-acquisition-units/pt_BR.json
translations/ui-acquisition-units/pt_PT.json
translations/ui-acquisition-units/zh_CN.json

Update translation strings as of 20190718T013203

---

translations/ui-acquisition-units/zh_CN.json

Update translation strings as of 20190718T220243

---

src/settings/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEditorContainer.js
src/settings/AcquisitionUnits/reducer.js
translations/ui-acquisition-units/en.json

Update wording and check boxes for Acquisitions Unit settings
To make the acquisitions unit settings wording and defaults less confusing
https://issues.folio.org/browse/UIAC-7
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be …

UIAC-7 review changes

---

translations/ui-acquisition-units/ca.json
translations/ui-acquisition-units/da.json
translations/ui-acquisition-units/de.json
translations/ui-acquisition-units/en_GB.json
translations/ui-acquisition-units/en_SE.json
translations/ui-acquisition-units/en_US.json
translations/ui-acquisition-units/es.json
translations/ui-acquisition-units/es_419.json
translations/ui-acquisition-units/es_ES.json
translations/ui-acquisition-units/fr.json
translations/ui-acquisition-units/fr_FR.json
translations/ui-acquisition-units/hu.json
translations/ui-acquisition-units/it_IT.json
translations/ui-acquisition-units/pt_PT.json

Update translation strings as of 20190807T131714

---

translations/ui-acquisition-units/pt_BR.json

Update translation strings as of 20190809T200806

---

translations/ui-acquisition-units/it_IT.json

Update translation strings as of 20190823T083240

---

translations/ui-acquisition-units/it_IT.json

Update translation strings as of 20190913T225241

---

translations/ui-acquisition-units/it_IT.json

Update translation strings as of 20190919T124724

---

translations/ui-acquisition-units/zh_CN.json

Update translation strings as of 20190925T125755

---

translations/ui-acquisition-units/ar.json

Update translation strings as of 20191004T135530

---

src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMemberships.js

https://issues.folio.org/browse/UIF-72 …

UIF-72 fix unit memebers display when personal info is not defined

---

translations/ui-acquisition-units/it_IT.json

Update translation strings as of 20191106T134035

---

translations/ui-acquisition-units/fr_FR.json

Update translation strings as of 20191118T154404

---

translations/ui-acquisition-units/fr_FR.json

Update translation strings as of 20191119T231120

---

translations/ui-acquisition-units/fr_FR.json

Update translation strings as of 20191125T160504

---

translations/ui-acquisition-units/fr_FR.json

Update translation strings as of 20191127T181804

---

translations/ui-acquisition-units/ru.json

Update translation strings as of 20191203T022312

---

translations/ui-acquisition-units/es_ES.json

Update translation strings as of 20191216T200945

---

translations/ui-acquisition-units/es.json
translations/ui-acquisition-units/es_419.json

Update translation strings as of 20191220T210632

---

translations/ui-acquisition-units/zh_CN.json

Update translation strings as of 20200109T152437

---

CHANGELOG.md
README.md

https://issues.folio.org/browse/UIAC-5 …

UIAC-5 update readme

---

translations/ui-acquisition-units/it_IT.json

Update translation strings as of 20200206T141023

---

translations/ui-acquisition-units/ja.json

Update translation strings as of 20200413T183215

---

translations/ui-acquisition-units/ja.json

Update translation strings as of 20200415T223222

---

translations/ui-acquisition-units/ja.json

Update translation strings as of 20200420T134821

---

translations/ui-acquisition-units/zh_TW.json

Update translation strings as of 20200424T193712

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIAC-17 …

UIAC-17 Update to Stripes v4

---

translations/ui-acquisition-units/fr_FR.json

Update translation strings as of 20200526T141248

---

translations/ui-acquisition-units/ru.json

Update translation strings as of 20200626T180122

---

package.json

upgrade stripes v5

---

package.json
src/settings/AcquisitionUnits/AcquisitionUnits.js
test/bigtest/network/factories/unit.js

Bump up libs

---

translations/ui-acquisition-units/es_419.json
translations/ui-acquisition-units/hi_IN.json
translations/ui-acquisition-units/ja.json
translations/ui-acquisition-units/ko.json

Update translation strings as of 20200921T192032

---

translations/ui-acquisition-units/it_IT.json

Update translation strings as of 20201111T142927

---

CHANGELOG.md
PERSONAL_DATA_DISCLOSURE.md

https://issues.folio.org/browse/UIAC-24 …

UIAC-24 Add personal data disclosure form

---

CHANGELOG.md
package.json
translations/ui-acquisition-units/en.json

https://issues.folio.org/browse/UIAC-26 …

UIAC-26 Update permission label

---

package.json
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMemberships.js
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMembershipsContainer.js

upgrade stripes v6 and fix some warnings

---

.eslintrc
test/bigtest/.eslintrc

fix eslint for workspaces

---

package.json

https://issues.folio.org/browse/UIAC-27 …

UIAC-27 Update stripes-cli to v2

---

.gitignore
jest.config.js
package.json
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetails.test.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsActions.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsActions.test.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsContainer.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsContainer.test.js

https://issues.folio.org/browse/FAT-39 …

FAT-39 unit tests for AcquisitionUnitDetails

---

src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMemberships.js
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMemberships.test.js
src/settings/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsList.test.js
src/settings/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsListContainer.test.js

https://issues.folio.org/browse/FAT-39 …

FAT-39 unit tests for AcquisitionUnitsList

---

CHANGELOG.md
Jenkinsfile
package.json

https://issues.folio.org/browse/UIAC-29 …

UIAC-29 Compile Translation Files into AST Format

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIAC-30 …

UIAC-30 Refine permissions

---

CHANGELOG.md
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMemberships.js
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMemberships.test.js
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMembershipsContainer.js
test/bigtest/network/factories/group.js
test/bigtest/network/factories/membership.js
test/bigtest/network/factories/unit.js
test/bigtest/network/factories/user.js
test/bigtest/tests/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsList-test.js

https://issues.folio.org/browse/UIAC-34 …

UIAC-34 Users assigned to an acquisitions unit should display in alphabetical order

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIAC-33 …

UIAC-33 increment stripes to v7

---

CHANGELOG.md
src/settings/AcquisitionUnits/resources.js

https://issues.folio.org/browse/UIAC-38 …

UIAC-38 Acq Unit settings not in alpha order

---

CHANGELOG.md
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetails.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetails.test.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsActions.js
src/settings/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEditor.js
src/settings/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEditor.test.js
src/settings/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEditorContainer.js
src/settings/AcquisitionUnits/AcquisitionUnits.js
src/settings/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsList.js
src/settings/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsList.test.js

https://issues.folio.org/browse/UIAC-39 …

UIAC-39 Settings (Acquisition units) | Apply baseline keyboard shortcuts

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIAC-41 …

UIAC-41 refactor psets away from backend '.all' permissions

---

CHANGELOG.md
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetails.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsActions.js

https://issues.folio.org/browse/UIAC-45 …

UIAC-45 ui-acquisition-units accessibility analysis

---

CHANGELOG.md
package.json
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMemberships.js
translations/ui-acquisition-units/en.json

https://issues.folio.org/browse/UIAC-49 …

UIAC-49 Add perm for managing acq unit assignments

---

CHANGELOG.md
package.json

https://issues.folio.org/browse/UIAC-55 …

UIAC-55 loose plugin dependencies permit incompatible versions

---

CHANGELOG.md
package.json

Also upgrade `stripes` to `v8`, and `stripes-acq-components` to `v4`.

UIAC-62 Upgrade `react-redux` to `v8`

---

CHANGELOG.md
src/settings/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEditor.js
src/settings/AcquisitionUnits/AcquisitionUnitEditor/AcquisitionUnitEditor.test.js

[UIAC-75](https://issues.folio.org/browse/UIAC-75) - UIAC-75: add description field for settings
https://github.com/folio-org/ui-acquisition-units/assets/116072773/006339ef-759d-4cdd-bffe-7e45e80b73a4
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is …

UIAC-75: add description field for settings

---

CHANGELOG.md
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetails.js
src/settings/AcquisitionUnits/AcquisitionUnitDetails/AcquisitionUnitDetailsActions.js
src/settings/AcquisitionUnits/AcquisitionUnitMemberships/AcquisitionUnitMemberships.js
src/settings/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsList.js
src/settings/AcquisitionUnits/AcquisitionUnitsList/AcquisitionUnitsListContainer.js

UIAC-80 React v19: refactor away from default props for functional components
